name: buypower_clone
description: BuyPower clone app built with flutter and stacked framework

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.17

  # State Management
  stacked: ^3.1.0-beta.0
  stacked_services: ^0.9.8

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

  stacked_generator: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/

flutter_native_splash:
  background_image: "assets/png/splashscreen.png"

  web: false
